### PR TITLE
Allow access to the gnupg workspace

### PR DESCRIPTION
**Pull request by optimumtact**
required to verify gpg signings etc if people want to set that up.

### CODE REVIEW

**Comment by nurupo** [comment]
Not sure if we want to allow write access into there. `~/.gnupg` is where user-added trusted keys are stored. Do we really want to allow every single job to add keys into there?

**Comment by tux3** [comment]
The keys should be stored in each job's workspace, not globally.
Everything runs under the same user (jenkins), so even just read access means any job could steal other people's private keys, this completely negates the point of confining jobs.

**Comment by nurupo** [comment]
Oh, the reason why oranges has created this issue is because I wanted to verify OpenSSL signature, not store my own keys. But yeah, if someone does store a key in there, it would be bad.

**Comment by optimumtact** [comment]
Nobody should be storing any key material on the build servers at all

**Comment by tux3** [comment]
Then if you only want to verify signatures, it would make more sense to set the permissions to read-only than read-write.

**Comment by optimumtact** [comment]
I had assumed it was trying to write some temp files in there.

I'll update the pr

**Pull request merged**
